### ISSUE TITLE
En tant qu'utilisateur, je veux avoir une fonctionnalité qcm afin d'apprendre en m'amusant

### ISSUE THREAD

**Issue by Saladin88** [Saladin88/SoninKrala#2]
En tant qu'user, je veux pouvoir avoir une rubrique avec des questions relatives à l'apprentissage de la langue et un choix à faire parmi plusieurs propositions. Pour ce faire, je dois : 

- [x] Creation Zoning, Wireframe, Graphic chart for View Quiz : #11 ;
- [x] [DATA] Établir mes MCD/MLD et MPD en bdd Fonctionnalité associée :  #6  ;
- [x] [INFRA] Établir l'implémentation cotée API (entité, endpoint, controller, validators, etc) Fonctionnalité associée : #7 ;
- [ ] [FRONT] Établir l'implémentation cotée Front user UI /UX Fonctionnalité associée :  #8  ;
